- id: '1642513883937'
  alias: Zigbee2MQTT - Magic Cube Wohnzimmer
  description: ''
  use_blueprint:
    path: golles/zigbee2mqtt_aqara_magic_cube.yaml
    input:
      remote: sensor.cube_wohnzimmer_action
      rotate_left_side_0:
      - service: media_player.volume_set
        data:
          volume_level: '{% set volume = state_attr(''media_player.denon_avr_x1200w'',
            ''volume_level'') | float - 0.05 %} {% if volume > 0.03 %}{{volume}}{%
            else %}0.03{% endif %}'
        target:
          entity_id: media_player.denon_avr_x1200w
      rotate_right_side_0:
      - service: media_player.volume_set
        data:
          volume_level: '{% set volume = state_attr(''media_player.denon_avr_x1200w'',
            ''volume_level'') | float + 0.05 %} {% if volume < 0.40 %}{{volume}}{%
            else %}0.40{% endif %}'
        target:
          entity_id: media_player.denon_avr_x1200w
      tap_side_0:
      - service: switch.toggle
        target:
          entity_id: switch.denon_qs1
      rotate_right_side_5:
      - device_id: 93f0e0715cbf2fa1bfec9c23d69d3ef2
        domain: light
        entity_id: light.wohnzimmer_decke
        type: brightness_increase
      rotate_left_side_5:
      - device_id: 93f0e0715cbf2fa1bfec9c23d69d3ef2
        domain: light
        entity_id: light.wohnzimmer_decke
        type: brightness_decrease
