switch:
  - platform: template
    switches:
      beamer_livingroom:
        friendly_name: "Beamer Wohnzimmer"
        unique_id: "switch_beamer_wohnzimmer"
        value_template: "{{ states('sensor.gosund_beamer_energy_power') | float(0) > 75 }}"
        availability_template: "{{ is_state('switch.gosund_beamer_power', 'on') }}"
        turn_on:
          service: remote.send_command
          data:
            entity_id: remote.rm3_wohnzimmer_remote
            device: beamer
            command: power
            num_repeats: 2
            delay_secs: 0.5
        turn_off:
          service: remote.send_command
          data:
            entity_id: remote.rm3_wohnzimmer_remote
            device: beamer
            command: power
            num_repeats: 2
            delay_secs: 0.5
        icon_template: mdi:projector

automation:
  - id: wohnzimmer_projector
    alias: "Wohnzimmer: Projektor on -> Turn Receiver & AppleTV on"
    trigger:
      - platform: state
        entity_id: switch.beamer_livingroom
        from: "off"
        to: "on"
        for:
          hours: 0
          minutes: 0
          seconds: 1
          milliseconds: 0
    condition: []
    action:
      - service: remote.send_command
        data:
          device: apple_remote_ir
          command: menu
          num_repeats: 2
        target:
          entity_id: remote.rm3_wohnzimmer_remote
      - condition: state
        entity_id: media_player.denon_avr_x1200w
        state: "off"
      - service: switch.turn_on
        target:
          entity_id: switch.denon_qs2
    mode: single
