scene:
  - id: kueche_morgens
    name: "Kueche: Morgens"
    entities:
      light.kueche:
        color_mode: color_temp
        brightness: 128
        color_temp: 366
        state: "on"
    icon: mdi:countertop-outline
  - id: kueche_tagsueber
    name: "Kueche: Tagsueber"
    entities:
      light.kueche:
        color_mode: color_temp
        brightness: 254
        color_temp: 370
        state: "on"
    icon: mdi:countertop
  - id: kueche_nachts
    name: "Kueche: Nachts"
    entities:
      light.kueche:
        color_mode: color_temp
        brightness: 38
        color_temp: 370
        state: "on"
    icon: mdi:countertop-outline

automation:
  - id: kueche_motion_activate_light
    alias: "Kueche: Motion activated Lights"
    use_blueprint:
      path: networkingcat/yet_another_motion_automation.yaml
      input:
        motion_entity: binary_sensor.motion_kueche_occupancy
        light_target:
          entity_id:
            - light.kueche
        no_motion_wait: 180
        scene_morning: scene.kueche_morgens
        scene_day: scene.kueche_tagsueber
        scene_evening: scene.kueche_morgens
        scene_night: scene.kueche_nachts
        time_scene_morning: "05:00:00"
        time_scene_day: "10:00:00"
        time_scene_evening: "22:00:00"
        time_scene_night: "23:00:00"
