input_text:
  remote_flur_tuer_last_event:
    name: Remote Flur Tuer Entry Last Event
    icon: mdi:remote

automation:
  - id: remote_flur_tuer
    alias: "Remote: Eingangstür"
    use_blueprint:
      path: EPMatt/ikea_e1743.yaml
      input:
        helper_last_controller_event: input_text.remote_flur_tuer_last_event
        integration: Zigbee2MQTT
        controller_entity: sensor.remote_flur_tuer_action
        action_button_up_short:
          - service: automation.trigger
            data:
              skip_condition: true
            target:
              entity_id: automation.arriving_at_home
        action_button_down_short:
          - service: automation.trigger
            data:
              skip_condition: true
            target:
              entity_id: automation.alles_aus
