# humidity
- platform: statistics
  name: Bad Humidity mean over last 24 hours
  entity_id: sensor.ble_humidity_xiaomi_bad
  state_characteristic: mean
  sampling_size: 86400
  max_age:
    hours: 24

- platform: statistics
  name: Bad humidity change over 5 minutes
  entity_id: sensor.ble_humidity_xiaomi_bad
  state_characteristic: change
  max_age:
    minutes: 5
  sampling_size: 50
  precision: 1

- platform: derivative
  name: Bad Humidity derivative
  source: sensor.ble_humidity_xiaomi_bad
  unit_time: min
  time_window: "00:10:00"

# Temperature
- platform: statistics
  name: Bad Temperature mean over last 24 hours
  entity_id: sensor.ble_temperature_xiaomi_bad
  state_characteristic: mean
  sampling_size: 86400
  max_age:
    hours: 24

- platform: derivative
  source: sensor.ble_temperature_xiaomi_bad
  name: Bad Temperature change per hour
  round: 1
  unit_time: h
  time_window: "00:30:00"

# bewegungscounter
- platform: statistics
  name: Bad Bewegungszähler 24h
  entity_id: binary_sensor.shelly_motion_bad_motion
  state_characteristic: count
  sampling_size: 86400
  max_age:
    hours: 24
