# humidity
- platform: statistics
  name: Bad Humidity mean over last 24 hours
  entity_id: sensor.ble_xiaomi_bad_humidity
  state_characteristic: mean
  sampling_size: 86400
  max_age:
    hours: 24

- platform: statistics
  name: Bad humidity change over 5 minutes
  entity_id: sensor.ble_xiaomi_bad_humidity
  state_characteristic: change
  sampling_size: 50
  precision: 1
  max_age:
    minutes: 5

# Temperature
- platform: statistics
  name: Bad Temperature mean over last 24 hours
  entity_id: sensor.ble_xiaomi_bad_temperature
  state_characteristic: mean
  sampling_size: 2880
  max_age:
    hours: 24

- platform: statistics
  name: Bad Temperature change over 5 minutes
  entity_id: sensor.ble_xiaomi_bad_temperature
  state_characteristic: change
  sampling_size: 50
  precision: 1
  max_age:
    minutes: 5

# bewegungscounter
- platform: history_stats
  name: Bad Bewegungszähler Heute
  entity_id: binary_sensor.shelly_motion_bad_motion
  state: "on"
  type: count
  start: "{{ states('sensor.timestamp_start_of_today') | float(0) }}"
  end: "{{ now() }}"
