# Temperature
- platform: statistics
  name: Flur Temperature mean over last 24 hours
  entity_id: sensor.ble_xiaomi_flur_temperature
  state_characteristic: mean
  sampling_size: 2880
  max_age:
    hours: 24

- platform: statistics
  name: Flur Temperature change over 5 minutes
  entity_id: sensor.ble_xiaomi_flur_temperature
  state_characteristic: change
  sampling_size: 50
  precision: 1
  max_age:
    minutes: 5

- platform: statistics
  name: Servereck Temperature mean over last 24 hours
  entity_id: sensor.ble_xiaomi_servereck_temperature
  state_characteristic: mean
  sampling_size: 2880
  max_age:
    hours: 24

- platform: statistics
  name: Servereck Temperature change over 5 minutes
  entity_id: sensor.ble_xiaomi_servereck_temperature
  state_characteristic: change
  sampling_size: 50
  precision: 1
  max_age:
    minutes: 5

# bewegungscounter
- platform: history_stats
  name: Flur Bewegungszähler Heute
  entity_id: binary_sensor.unifi_g3_flex_flur_motion
  state: "on"
  type: count
  start: "{{ states('sensor.timestamp_start_of_today') | float(0) }}"
  end: "{{ now() }}"
