- platform: template
  sensors:
    ha_entities_count:
      value_template: "{{states | count}}"
      unit_of_measurement: "items"
      attribute_templates:
        alarm_control_panel: "{{states['alarm_control_panel'] | count}}"
        alert: "{{states['alert'] | count}}"
        automation: "{{states['automation'] | count}}"
        binary_sensor: "{{states['binary_sensor'] | count}}"
        button: "{{states['button'] | count}}"
        camera: "{{states['camera'] | count}}"
        climate: "{{states['climate'] | count}}"
        counter: "{{states['counter'] | count}}"
        device_tracker: "{{states['device_tracker'] | count}}"
        fan: "{{states['fan'] | count}}"
        group: "{{states['group'] | count}}"
        image_processing: "{{states['image_processing'] | count}}"
        input_boolean: "{{states['input_boolean'] | count}}"
        input_button: "{{states['input_button'] | count}}"
        input_datetime: "{{states['input_datetime'] | count}}"
        input_number: "{{states['input_number'] | count}}"
        input_select: "{{states['input_select'] | count}}"
        input_text: "{{states['input_text'] | count}}"
        light: "{{states['light'] | count}}"
        lock: "{{states['lock'] | count}}"
        media_player: "{{states['media_player'] | count}}"
        number: "{{states['number'] | count}}"
        person: "{{states['person'] | count}}"
        remote: "{{states['remote'] | count}}"
        scene: "{{states['scene'] | count}}"
        script: "{{states['script'] | count}}"
        select: "{{states['select'] | count}}"
        sensor: "{{states['sensor'] | count}}"
        sun: "{{states['sun'] | count}}"
        switch: "{{states['switch'] | count}}"
        timer: "{{states['timer'] | count}}"
        update: "{{states['update'] | count}}"
        vacuum: "{{states['vacuum'] | count}}"
        weather: "{{states['weather'] | count}}"
        zone: "{{states['zone'] | count}}"
