# bewegungscounter
- platform: statistics
  name: Küche Bewegungszähler 24h
  entity_id: binary_sensor.shelly_motion_kuche_motion
  state_characteristic: count
  sampling_size: 86400
  max_age:
    hours: 24
