- platform: systemmonitor
  resources:
    - type: processor_temperature
    - type: disk_use_percent
      arg: "/"
    - type: memory_use_percent
    - type: throughput_network_in
      arg: enp0s18
    - type: throughput_network_out
      arg: enp0s18
    - type: network_in
      arg: enp0s18
    - type: network_out
      arg: enp0s18
    - type: processor_use
    - type: last_boot
    - type: load_1m
    - type: load_5m
    - type: load_15m

- platform: websocket_api
