#
# Backlight LED
#
- platform: template
  switches:
    monitor_hintergrund:
      friendly_name: "Monitor Hintergrundlicht"
      unique_id: "switch_monitor_hintergrund"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: ledstrip_monitor
          command: power_on
      turn_off:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: ledstrip_monitor
          command: power_off
      icon_template: mdi:monitor
