#
# Beamer Wohnzimmer
#
- platform: template
  switches:
    beamer_livingroom:
      friendly_name: "Beamer Wohnzimmer"
      unique_id: "switch_beamer_wohnzimmer"
      value_template: "{{ states('sensor.beamer_energy_power') | float(0) > 75 }}"
      availability_template: "{{ is_state('switch.beamer', 'on') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: beamer
          command: power
          num_repeats: 2
          delay_secs: 0.5
      turn_off:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: beamer
          command: power
          num_repeats: 2
          delay_secs: 0.5
      icon_template: mdi:projector
