#
# Denon Switches
#   - Power
#.  - Quickselect 1-3
#
- platform: template
  switches:
    denon_power:
      friendly_name: "Denon Power IR"
      unique_id: "switch_denon_power"
      value_template: "{{ states('media_player.denon_avr_x1200w') != 'off' }}"
      availability_template: "{{ is_state('switch.mediaeck', 'on') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: denonavr
          command: power
          num_repeats: 1
      turn_off:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: denonavr
          command: power
          num_repeats: 1
      icon_template: mdi:audio-video

- platform: template
  switches:
    denon_qs1:
      friendly_name: "DENON ETN.fm"
      unique_id: "switch_denon_qs1"
      value_template: "{{ is_state_attr('media_player.denon_avr_x1200w', 'media_artist', 'ETN.FM 1 - Trance Channel') }}"
      turn_on:
        service: script.denon_etnfm
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.denon_power
      icon_template: mdi:radio

- platform: template
  switches:
    denon_qs2:
      friendly_name: "DENON AppleTV"
      unique_id: "switch_denon_qs2"
      value_template: "{{ is_state_attr('media_player.denon_avr_x1200w', 'source', 'AppleTV') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: denonavr
          command: quick_2
          num_repeats: 1
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.denon_power
      icon_template: mdi:apple

- platform: template
  switches:
    denon_qs3:
      friendly_name: "DENON Recalbox"
      unique_id: "switch_denon_qs3"
      value_template: "{{ is_state_attr('media_player.denon_avr_x1200w', 'source', 'RecalBox') }}"
      turn_on:
        service: remote.send_command
        data:
          entity_id: remote.rm3_wohnzimmer_remote
          device: denonavr
          command: quick_3
          num_repeats: 1
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.denon_power
      icon_template: mdi:gamepad-variant

- platform: template
  switches:
    denon_qs4:
      friendly_name: "DENON Radio 90s"
      unique_id: "switch_denon_qs4"
      value_template: "{{ is_state_attr('media_player.denon_avr_x1200w', 'media_artist', 'Sunshine Live - 90er') }}"
      turn_on:
        service: script.denon_sunshine90
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.denon_power
      icon_template: mdi:radio
