input_text:
  remote_schlafzimmer_rollo_remote_last_event:
    name: Remote Schlafzimmer Rollo Last Event
    icon: mdi:remote

automation:
  - id: remote_schlafzimmer_rollo
    alias: "Remote: Schlafzimmer Rollo"
    use_blueprint:
      path: EPMatt/ikea_e1766.yaml
      input:
        helper_last_controller_event: input_text.remote_schlafzimmer_rollo_remote_last_event
        integration: Zigbee2MQTT
        controller_entity: sensor.remote_schlafzimmer_rollo_action
        action_button_up_short:
          - service: cover.set_cover_position
            data:
              position: 0
            target:
              device_id: 01facedecd0f44490b4cf98e6eba44e5
        action_button_up_double:
          - service: cover.stop_cover
            data: {}
            target:
              device_id: 01facedecd0f44490b4cf98e6eba44e5
        action_button_down_short:
          - service: cover.set_cover_position
            data:
              position: 100
        action_button_down_release:
          - service: cover.stop_cover
            data: {}
