automation:
  - id: schlafzimmer_bedtime
    alias: "Schlafzimmer: 10pm / Before Bedtime"
    description: ""
    trigger:
      - platform: time
        at: "22:00:00"
    condition:
      - condition: state
        entity_id: group.residents
        state: home
      - condition: state
        entity_id: binary_sensor.fenster_schlafzimmer_contact
        state: "off"
    action:
      - service: cover.set_cover_position
        data:
          position: 50
        target:
          entity_id: cover.schlafzimmer_rollo
    mode: single
