input_text:
  remote_schlafzimmer_remote_bett_last_event:
    name: Remote Schlafzimmer Bett Last Event
    icon: mdi:remote

automation:
  - id: remote_schlafzimmer_bett
    alias: "Remote: Schlafzimmer Bett"
    use_blueprint:
      path: EPMatt/ikea_e1743.yaml
      input:
        helper_last_controller_event: input_text.remote_schlafzimmer_bett_last_event
        integration: Zigbee2MQTT
        controller_entity: sensor.remote_schlafzimmer_bett_action
        action_button_up_short:
          - parallel:
              - service: automation.trigger
                data:
                  skip_condition: true
                target:
                  entity_id: automation.arriving_at_home
              - device_id: 01facedecd0f44490b4cf98e6eba44e5
                domain: cover
                entity_id: cover.schlafzimmer_rollo
                type: set_position
                position: 100
        action_button_down_short:
          - parallel:
              - service: automation.trigger
                data:
                  skip_condition: true
                target:
                  entity_id: automation.alles_aus
              - device_id: 01facedecd0f44490b4cf98e6eba44e5
                domain: cover
                entity_id: cover.schlafzimmer_rollo
                type: set_position
                position: 0
