- platform: group
  name: residents
  services:
    - service: mobile_app_maexphone
    - service: mobile_app_maexpad

- platform: group
  name: max
  services:
    - service: mobile_app_maexphone
    - service: mobile_app_maexpad

- platform: telegram
  name: max_telegram
  chat_id: !secret telegram_bot_chatid_max
