- platform: group
  name: all_phones
  services:
    - service: mobile_app_minimaex

- platform: group
  name: max
  services:
    - service: mobile_app_minimaex
    - service: mobile_app_maexpad

- platform: telegram
  name: max_telegram
  chat_id: !secret telegram_bot_chatid_max
