automation:
  - id: backup_full_weekly
    alias: "Auto-Backup: Full Weekly"
    description: ""
    trigger:
      - platform: time
        id: backup-weekly-full
        at: 01:30:00
    condition:
      - condition: time
        weekday:
          - fri
    action:
      - service: hassio.backup_full
        data:
          name: full-{{ now().strftime('%Y-%m-%d') }}
    mode: single

  - id: backup_daily_config
    alias: "Auto-Backup: Config Daily"
    description: ""
    trigger:
      - platform: time
        id: backup-daily-partial
        at: 01:00
    condition: []
    action:
      - service: hassio.backup_partial
        data:
          folders:
            - homeassistant
            - addons/local
            - media
            - ssl
            - share
          name: partial-{{ now().strftime('%Y-%m-%d') }}
    mode: single

  - id: backup_rsync
    alias: "Auto-Backup: rclone offsite daily"
    description: ""
    trigger:
      - platform: time
        id: remote-backup
        at: 05:00:00
    condition: []
    action:
      - service: hassio.addon_start
        data:
          addon: 2ca71ec5_rclone
    mode: single
