scene:
  - id: bad_morgens
    name: "Bad: Morgens"
    entities:
      light.bad:
        color_mode: color_temp
        brightness: 100
        color_temp: 366
        state: "on"
    icon: mdi:bathtub-outline
  - id: bad_tagsueber
    name: "Bad: Tagsueber"
    entities:
      light.bad:
        color_mode: brightness
        brightness: 254
        state: "on"
    icon: mdi:bathtub
  - id: bad_nachts
    name: "Bad: Nachts"
    entities:
      light.bad_decke:
        state: "off"
      light.bad_spiegel_1:
        state: "off"
      light.bad_spiegel_2:
        color_mode: color_temp
        brightness: 13
        color_temp: 366
        state: "on"
      light.bad_spiegel_3:
        state: "off"
    icon: mdi:bathtub-outline

automation:
  - id: bad_motion_activate_light
    alias: "Bad: Motion activated Light"
    use_blueprint:
      path: networkingcat/yet_another_motion_automation.yaml
      input:
        motion_entity: binary_sensor.shelly_motion_bad_motion
        light_target:
          entity_id:
            - light.bad
        no_motion_wait: 180
        no_motion_blocker: input_boolean.shower_mode
        no_motion_blocker_boolean: false
        scene_morning: scene.bad_morgens
        scene_day: scene.bad_tagsueber
        scene_evening: scene.bad_morgens
        scene_night: scene.bad_nachts
        time_scene_morning: "05:00:00"
        time_scene_day: "09:00:00"
        time_scene_evening: "22:00:00"
        time_scene_night: "23:00:00"
