input_text:
  remote_flur_tuer_last_event:
    name: Remote Flur Tuer Entry Last Event
    icon: mdi:remote
    min: 0
    max: 255

automation:
  - id: remote_flur_tuer
    alias: "Remote: Eingangstür"
    use_blueprint:
      path: EPMatt/ikea_e1743.yaml
      input:
        helper_last_controller_event: input_text.remote_flur_tuer_last_event
        integration: Zigbee2MQTT
        controller_entity: sensor.remote_flur_tuer_action
        action_button_up_short:
          - scene: scene.coming_home
        action_button_down_short:
          - scene: scene.alles_aus
