automation:
  - id: shellies_announce
    alias: "Shellies: Announce"
    trigger:
      - platform: homeassistant
        event: start
      - platform: time_pattern
        hours: /1
    action:
      service: mqtt.publish
      data:
        topic: shellies/command
        payload: announce

  - id: shellies_discovery
    alias: "Shellies: Discovery"
    trigger:
      - platform: mqtt
        topic: shellies/announce
    action:
      - service: python_script.shellies_discovery
        data:
          id: "{{ trigger.payload_json.id }}"
          mac: "{{ trigger.payload_json.mac }}"
          fw_ver: "{{ trigger.payload_json.fw_ver }}"
          model: "{{ trigger.payload_json.model }}"
          mode: "{{ trigger.payload_json.mode | default }}"
          host: "{{ trigger.payload_json.ip }}"
    mode: queued
    max: 999

  - id: shellies_announce_gen2
    alias: "Shellies Announce Gen2"
    trigger:
      - platform: homeassistant
        event: start
    variables:
      device_info_payload: "{{ {'id': 1, 'src':'shellies_discovery', 'method':'Shelly.GetConfig'} | to_json }}"
      device_ids: [] # enter the list of device IDs here
    action:
      - repeat:
          for_each: "{{ device_ids }}"
          sequence:
            - service: mqtt.publish
              data:
                topic: "{{ repeat.item }}/rpc"
                payload: "{{ device_info_payload }}"

  - id: shellies_discovery_gen2
    alias: "Shellies Discovery Gen2"
    mode: queued
    max: 999
    trigger:
      - platform: mqtt
        topic: shellies_discovery/rpc
    action:
      - service: python_script.shellies_discovery_gen2
        data:
          id: "{{ trigger.payload_json.src }}"
          device_config: "{{ trigger.payload_json.result }}"
