input_boolean:
  dark_mode:
    initial: true
    name: Theme Dark mode
    icon: mdi:theme-light-dark

input_select:
  theme:
    options:
      - default
      - blue-red
      - dark-blue
      - dark-green
      - light-blue
      - light-green
      - orange
      - red
    icon: mdi:theme-light-dark
    initial: blue-red
    name: Theme Selection

automation:
  - id: frontend_theme_darkmode_on
    alias: "Frontend: turn on dark mode during night"
    trigger:
      - platform: time
        at: "20:00"
      - platform: sun
        event: sunset
    condition: "{{ is_state('input_boolean.dark_mode', 'off') }}"
    action:
      entity_id: input_boolean.dark_mode
      service: input_boolean.turn_on

  - id: frontend_theme_lightmode_on
    alias: "Frontend: turn on light mode on during day"
    trigger:
      - platform: time
        at: "06:00"
      - platform: sun
        event: sunrise
    condition: "{{ is_state('input_boolean.dark_mode', 'on') }}"
    action:
      entity_id: input_boolean.dark_mode
      service: input_boolean.turn_off

  - alias: "Frontend: change ui theme"
    trigger:
      - platform: state
        entity_id: input_select.theme
      - platform: state
        entity_id: input_boolean.dark_mode
      - platform: homeassistant
        event: start
    action:
      service: frontend.set_theme
      data:
        name: >
          {% if is_state("input_select.theme", "default") %}
            default
          {% else %}
            {% set mode = "dark" if is_state("input_boolean.dark_mode", "on") else "light" -%}
            {% set name = states("input_select.theme") -%}
            ios-{{ mode }}-mode-{{ name }}
          {% endif %}
        mode: "dark"
