automation:
  - id: upgrade_notification_homeassistant
    alias: "Updates: Send Notification of new major Home-Assistant Version released"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - update.home_assistant_core_update
        from: "off"
        to: "on"
      - platform: time
        at: "19:10:00"
    condition:
      - condition: template
        value_template: |-
          {{ is_state('update.home_assistant_core_update', 'on') 
              and state_attr('update.home_assistant_core_update','in_progress')
                  == False
              and state_attr('update.home_assistant_core_update','installed_version')[:7] 
                  != state_attr('update.home_assistant_core_update','latest_version')[:7] }}
    action:
      - service: notify.max
        data:
          title: New Major Home-Assistant Release 🚀
          message: HomeAssistant {{ state_attr('update.home_assistant_core_update','latest_version') }} was just released

  - id: upgrade_minor_version_of_homeassistant
    alias: "Updates: Update Home-Assistant Minor version automatically"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - update.home_assistant_core_update
        from: "off"
        to: "on"
      - platform: time
        at: "19:11:00"
    condition:
      - condition: template
        value_template: |-
          {{ is_state('update.home_assistant_core_update', 'on') 
              and state_attr('update.home_assistant_core_update','in_progress')
                  == False
              and state_attr('update.home_assistant_core_update','installed_version')[:7] 
                  == state_attr('update.home_assistant_core_update','latest_version')[:7] }}
    action:
      - service: notify.max
        data:
          title: Update Home-Assistant 🚀
          message: Updating from {{ state_attr('update.home_assistant_core_update','installed_version') }} to {{ state_attr('update.home_assistant_core_update','latest_version') }}
      - service: update.install
        data:
          backup: true
        target:
          entity_id: update.home_assistant_core_update

  - id: notification_hacs_updates
    alias: "Updates: HACS updates pending as persistent notification"
    trigger:
      - platform: time
        at: "14:00:00"
      - platform: state
        entity_id: sensor.hacs
    condition:
      - condition: template
        value_template: "{{ states(trigger.entity_id) != 'unknown'}}"
      - condition: template
        value_template: "{{ (states(trigger.entity_id) | float(0)) != 0}}"
    action:
      - service: persistent_notification.create
        data_template:
          title: Updates pending in HACS
          notification_id: hacs-update
          message:
            "{% for repo in state_attr(trigger.entity_id, 'repositories') %}\n\
            \  **{{ repo.display_name }}** _{{ repo[\"installed_version\"] }}_ -> _{{\
            \ repo[\"available_version\"] }}_\n{% endfor %}"
