automation:
  - id: vacation_mode_on
    alias: "Vacation mode: auto turn on"
    initial_state: true
    trigger:
      platform: state
      entity_id: group.residents
      from: home
      to: not_home
      for: "24:00:00"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.vacation_mode
      - service: switch.turn_on
        target:
          entity_id: switch.presence_simulation
      - service: notify.residents
        data:
          title: "Vacation mode"
          message: "No one at home for 24 hours, switching on vacation mode."

  - id: vacation_mode_off
    alias: "Vacation mode: auto turn off"
    initial_state: true
    trigger:
      platform: state
      entity_id: group.residents
      from: not_home
      to: home
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: "on"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.presence_simulation
      - service: input_boolean.turn_off
        entity_id: input_boolean.vacation_mode
      - service: notify.residents
        data:
          title: "Vacation mode"
          message: "Welcome back! Switching off the vacation mode."

  - id: vacation_mode_presence_simulation_on
    alias: "Vacation mode: presence simulation turn on"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.vacation_mode
      to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.presence_simulation

  - id: vacation_mode_presence_simulation_off
    alias: "Vacation mode: presence simulation turn off"
    initial_state: true
    trigger:
      platform: state
      entity_id: input_boolean.vacation_mode
      to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.presence_simulation

group:
  presence:
    name: Presence Simulation Group
    entities:
      - light.schlafzimmer_bett
      - switch.gosund_banana_power
